---
name: CI
on: push
jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/action-cxx-toolkit.v9.main:latest
        with:
          checks: build test install warnings
          cc: gcc
          cmakeflags: -DCMAKE_BUILD_TYPE=Release -DWITH_TESTS=On
          ctestflags: --test-dir /tmp/build/test
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lucteo/action-cxx-toolkit.v9.main:latest
        with:
          checks: clang-format
          clangformatdirs: src test
